- src/pages/split-condition/SplitCondition.test.tsx
- src/pages/split-condition/SplitCondition.tsx
- src/pages/split-condition/SplitConditionContainer.tsx
> Add tests for failure in fetching allowance

- .travis.yml
- travis/deploy_pull_request.sh
- travis/deploy_release.sh
- travis/prepare_production_deployment.sh
This is required to setup the CI/CD. The following configuration will
allow:
* PR-reviews auto deployments.
* develop branch auto deployments into dev environment.
* master branch auto deployments into staging environment.
* tag releases to request manual deployments into production
environment.
See #25
> Add Travis CI scripts

- src/pages/split-condition/InputAmount.tsx
Add a RegExp to check positionId value in InputAmount when get the
balance of the position after onchange position input.
Closes #33
> Add RegExp to check positionId value

- src/components/common/UserDropdown/index.tsx
- src/components/layout/Header/index.tsx
- src/contexts/Web3Context.tsx
> Fix disconnect state and action

- src/components/common/UserDropdown/index.tsx
This was pending from #89 
Closes #44
> Provider name

- src/components/common/SetAllowance/index.tsx
- src/hooks/useAllowanceState.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/SplitPosition/Form.test.tsx
- src/pages/SplitPosition/Form.tsx
- src/pages/SplitPosition/index.tsx
Closes #92 
One test is skipped because I couldn't fix it. I moved everything derived from allowance to another hook to ease integration in other components. This could be improved further (and fix tests) if not only collateral is present in the container `SplitFrom.tsx` but also `amount`, in this way we won't need to test that (or test the hook separately).
> Fix allowance stuck in loading

- src/components/buttons/ButtonCopy/index.tsx
- src/components/buttons/ButtonDots/index.tsx
- src/components/icons/Dots.tsx
- src/components/pureStyledComponents/TableWrapper.tsx
- src/components/table/CellHash.tsx
- src/pages/ConditionDetails/Wrapper.tsx
- src/pages/ConditionsList/index.tsx
- src/pages/ReportPayouts/OutcomesTable.tsx
- src/theme/globalStyle.tsx
- src/theme/tableStyles.js
- src/theme/tableStyles.tsx
Closes #84
I think it still works OK.
Dropdowns do nothing. I think they shouldn't be shown if the user is not connected, but I'm not sure (discuss?). Maybe we can ask the user to connect if they click on an item that needs them to be connected.
I used a monospaced font for addresses to achieve better alignment. I plan to replace it for a better looking one, but it'll do for now.
**Screenshots:**
> (Feature) Condition List table

- src/pages/ConditionsList/index.tsx
- src/pages/PositionsList/index.tsx
Closes #102
This was a little trickier than initially thought. Had to change quite a few things to get this working because component rendering was going completely crazy.
It seems to work fine now.
**Screenshots for user disconnected / connected:**
> (Feature) Position list table

- src/components/form/SelectCondition/index.tsx
- src/components/redeemPosition/SelectPosition/index.tsx
- src/pages/RedeemPosition/Contents.tsx
- src/pages/RedeemPosition/index.tsx
Closes #78 
Some (very slight) improvements over what @lmcorbalan did with this section.
> (Feature) Redeem Position

- src/pages/ConditionsList/index.tsx
- src/pages/PositionsList/index.tsx
Closes #122
Closes #124 
Thanks @lmcorbalan !
> Debounce input search for condition and position lists

- src/components/layout/Header/index.tsx
- src/theme/web3ModalCSS.tsx
Closes #141
Fixed.
Also fixed a few (simple) related things.
> (Fix) Components overlapping

- package.json
- src/components/buttons/ButtonConnect/index.tsx
- src/components/layout/Footer/index.tsx
- src/components/layout/Header/index.tsx
- src/theme/web3ModalCSS.tsx
- yarn.lock
Mmm something is breaking the web3modal styles at the build time. I think is the datatables, but I'm not 100% sure. The best solution I found was to set the correct styles in the web3Modal styles.
> Fix web3 modal

- src/components/form/InputAmount/index.tsx
- src/components/form/InputPosition/index.tsx
- src/components/form/SelectPositions/index.tsx
- src/contexts/MultiPositionsContext.tsx
- src/pages/SplitPosition/Form.tsx
- src/pages/SplitPosition/SplitFrom.tsx
- src/pages/SplitPosition/index.tsx
- src/queries/users.tsx
- src/services/conditionalTokens.ts
> Split Position - Select Position

- src/components/form/InputPosition/index.tsx
- src/components/splitPosition/PositionPreview/index.tsx
- src/hooks/useCollateral.tsx
- src/pages/SplitPosition/Form.tsx
- src/pages/SplitPosition/SplitFrom.tsx
- src/util/types.ts
> Split Position - Position Preview - Use Position collateral when splitting from position

- src/components/modals/SelectPositionsModal/index.tsx
- src/theme/dataTableCSS.tsx
Closes #74 
Not much to do, just fixed a few styling issues, changed some words, etc.
**Screenshot:**
> (Feature) Select Position Modal

- src/pages/PositionDetails/Contents.tsx
> Fix unused code

- src/pages/ConditionDetails/Wrapper.tsx
> Bug condition details spinner

- public/index.html
- src/components/table/CellHash/index.tsx
- src/types/generatedGQL.ts
Closes #177
It should look better now.
> (Feature) Better typography for addresses

- src/pages/ConditionDetails/Contents.tsx
> Add logic for condition details menu

- src/pages/ReportPayouts/Contents.tsx
- src/pages/ReportPayouts/OutcomesTable.tsx
Closes #200 
I've to move some code out of `OutcomesTable` component, anyways it had too much responsibility. Also, I did some little changes because the logic that lived in `OutcomesTable` was receiving a valid condition, and with these changes, it can be null and report that a disconnected user is not oracle for nothing.
> Show report button

- src/theme/dataTableCSS.tsx
Closes #219 
Should be fixed on both Positions and Conditions List.
> (fix) dropdown is cut

- src/config/constants.ts
- src/pages/PrepareCondition/index.tsx
> Add pattern ref in TextField `outcomeSlot` for Prepare Condition page

- src/components/form/Amount/index.tsx
- src/components/form/InputAddress/index.tsx
- src/components/modals/TransferOutcomeTokensModal/index.tsx
- src/components/modals/UnwrapModal/index.tsx
- src/contexts/PositionContext.tsx
- src/hooks/useBalanceForPosition.tsx
- src/hooks/usePositions.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/PositionDetails/Wrapper.tsx
- src/pages/PositionsList/index.tsx
- src/services/conditionalTokens.ts
- src/util/remoteData.ts
- src/util/tools.ts
- src/util/types.ts
Closes #138 
Closes #192 
For the position list, work like this..
For the condition details..
> [FE] - Position List - Add option to Transfer outcome tokens

- src/theme/dataTableCSS.tsx
> (fix) Table head cells text wrapping

- src/components/common/Warning/index.tsx
- src/components/form/InputCondition/index.tsx
- src/components/icons/AlertIcon.tsx
- src/contexts/ConditionContext.tsx
- src/pages/SplitPosition/Form.tsx
> Add check condition not resolved in `InputCondition` hook

- src/components/common/Dropdown/index.tsx
- src/components/form/InputAddress/index.tsx
- src/components/modals/TransferOutcomeTokensModal/index.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/PositionsList/index.tsx
- src/util/remoteData.ts
Closes #191
Only made a few changes to what @mariano-aguero implemented.
It should look like these:
> (Feature) Transfer outcome tokens

- src/components/common/UserDropdown/index.tsx
> Remove get provider name web3modal from `getWalletName`

- src/components/modals/SelectConditionModal/index.tsx
- src/components/modals/SelectPositionsModal/index.tsx
- src/components/splitPosition/DisplayTablePosition/index.tsx
> Add `paginationRowsPerPageOptions` to condition and position modals grid

- src/contexts/Web3Context.tsx
Closes #257 
Closes #206 
To test this:
- Create a condition
- Switch between accounts
-- Try to create condition with another account
- Switch networks
> Fix reload a page when user selects another wallet in Metamask

- src/pages/PrepareCondition/index.tsx
> Add required errors and change text message in prepare conditions form

- src/contexts/Web3Context.tsx
> Check `accounts.length`on accountsChanged events for Web3Context

- src/components/mergePositions/MergePreview/index.tsx
- src/contexts/Web3Context.tsx
- src/hooks/useIsPositionRelatedToCondition.tsx
- src/hooks/useWithToken.tsx
- src/pages/MergePositions/Contents.tsx
- src/pages/RedeemPosition/Contents.tsx
> Redeem positions: 'Position is not related to the condition.’ is displayed for a 1-2 sec when select a position

- src/components/form/InputAmount/index.tsx
- src/components/modals/TransferOutcomeTokensModal/index.tsx
- src/pages/MergePositions/Contents.tsx
- src/pages/PrepareCondition/index.tsx
Closes #274 
Closes #288 
Closes #266 
Closes #286
> Fix some minor issues

- src/hooks/usePositions.tsx
- src/pages/PositionsList/index.tsx
Closes #321 
Not sure if this code is 100% kosher, but it seems to work...
> (Fix) Sort by token symbol

- src/components/common/CookiesBanner/index.tsx
Addresses https://github.com/gnosis/conditional-tokens-explorer/issues/300#issuecomment-697459009
> (fix) Cookies banner for the built app

- src/components/mergePositions/MergeResultModal/index.tsx
Closes #332 
It looks like this
> Fix typo in positions table props

- src/hooks/useQuestion.tsx
> The report payout must be labeled correctly

- src/components/common/SetAllowance/index.tsx
> (fix) token unlock symbol

- src/components/statusInfo/common.tsx
- src/pages/RedeemPosition/Contents.tsx
Closes #339 
Changed "Waiting..." for a more appropriate "Working..."
And component's title is capitalized now.
> (Fix) Change all the waiting texts

- src/components/modals/SelectPositionsModal/index.tsx
> Incorrect sorting of the Amount column in the Positions pop-up

- src/pages/PositionDetails/Contents.tsx
> (Fix) Wording

- src/components/form/InputAmount/index.tsx
- src/components/pureStyledComponents/Textfield.tsx
> (fix) disable amount input

- src/components/modals/SelectPositionsModal/index.tsx
- src/pages/PositionsList/index.test.tsx
- src/pages/PositionsList/index.tsx
- src/queries/positions.tsx
> Implement default sort order for grid lines on the Conditions/Positions pages

- src/pages/ConditionDetails/Wrapper.tsx
> "OK" button on the Condition Details pop-up redirects user to the Positions list 

- src/components/common/SetAllowance/index.tsx
- src/components/form/SelectCollateral/index.tsx
- src/hooks/useAllowanceState.tsx
- src/hooks/useCollateral.tsx
- src/pages/SplitPosition/Form.tsx
- src/pages/SplitPosition/SplitFrom.tsx
- src/util/tools.ts
> Fix collateral token behaviors on split position

- src/components/form/InputAmount/index.tsx
> bracket is missing in the "Use Wallet Balance"

- src/components/form/DisplayTableConditions/index.tsx
> (fix) 404 error

- src/config/networkConfig.ts
Replace the current OWL address for Rinkeby network
> Update OWL rinkeby address

- src/components/modals/SelectConditionModal/index.tsx
- src/components/modals/SelectPositionsModal/index.tsx
Closes #201 
This opts for filter out selected positions/conditions from the list.
> (Feature) Remove or disable selected conditions / positions

- src/components/modals/SelectPositionsModal/index.tsx
- src/components/redeemPosition/PositionPreview/index.tsx
- src/hooks/usePositions.tsx
- src/hooks/useWithToken.tsx
- src/pages/RedeemPosition/Contents.tsx
> Inconsistent data across components of redeem position

- package.json
- src/components/common/BigNumberInput/index.tsx
- src/components/form/BigNumberInputWrapper/index.tsx
- yarn.lock
> [FE] Cannot lead with a period

- src/components/form/Amount/index.tsx
Closes #375 
Look like this ...
> [FE] Merge positions: Change 'Use Wallet Balance ($0.00)' message to 'Not Connected To Wallet' when a user is not logged in

- src/components/form/DisplayTableConditions/index.tsx
- src/components/modals/DisplayConditionsTableModal/index.tsx
- src/components/text/TitleValue/index.tsx
- src/pages/ConditionDetails/Contents.tsx
- src/pages/PositionDetails/Contents.tsx
Closes #379 
Some positions IDS with 2 or 3 conditions
0x573ac9fcf1e16ebf15fb2779ca54153a3cec8582d28d5d56210d1228cf6ec781
0xbf96e5419a5ddfa8ed7846252ab262e7a23bf46a4b9782d9cc7f05e3c6705b0a
0x5647c5cb905ecbacc9aa97d7954da4e358da04b4c9cecdadd2fdb827bb215fd1
> [FE] Change how the Condition ID is displayed in Position Details

- src/hooks/usePositions.tsx
> Convert address of collateral to lowercase before filtering

- src/components/form/InputPosition/index.tsx
- src/pages/SplitPosition/SplitFrom.tsx
> Fix typo and add click handler for open positions modal

- src/pages/ReportPayouts/Contents.tsx
> [FE] Report Payout: Validation message is still displayed on the form when remove Condition ID

- src/components/buttons/ButtonControl/index.tsx
- src/components/buttons/buttonStylingTypes.ts
- src/components/common/Dropdown/index.tsx
- src/components/form/AddOutcome/index.tsx
- src/components/form/CategoriesDropdown/index.tsx
- src/components/text/TitleValue/index.tsx
- src/pages/PrepareCondition/index.tsx
Closes #416
Closes #417
Closes #433
1) Regarding #416, this is what you should see now:
2) Regarding #417: 
- Enter / Return keys should save changes (if the new outcome text is valid)
- Esc key should cancel changes.
- Added a new "Cancel" button to make it more obvious that you can cancel an edit.
3) Regarding #433 ... it's complicated (see below).
- _"Currently, when an outcome value is too long (...)"_: That's OK, we're dealing with an input here, so we can't change height when text is too long. Any workaround for this would bee too complicated and / or unreliable. I just added a `...` which should show when text overflows the container, and a title for mouse hover. Tooltips seem like overkill, they will pop all the time and maybe end up being annoying.
- _"It would be nice not to …
> (Fix) Prepare Omen Condition Issues

- src/components/statusInfo/StatusInfoInline/index.tsx
- src/pages/PrepareCondition/index.tsx
> (Fix) Add "Prepare Omen Condition" date warning

- package.json
- src/contexts/Web3Context.tsx
- yarn.lock
> Disconect walletconnect

- src/components/filters/DateFilter/index.tsx
> [FE] Conditions list: Search returns no results when a creation date filter is filled with To=From date

- src/components/filters/DateFilter/index.tsx
- src/components/filters/MinMaxFilter/index.tsx
> [FE] Search results are not refreshed when clear out values in the 'Number of outcomes' and 'Created date' filters

- src/pages/ConditionsList/index.tsx
> [FE] Search returns an odd GraphQL error when search by numbers

- src/components/modals/SelectConditionModal/index.tsx
- src/theme/dataTableCSS.tsx
- src/theme/tableCustomStyles.tsx
> (fix) table cell wording

- src/components/filters/DateFilter/index.tsx
- src/config/constants.ts
- src/pages/ConditionsList/index.tsx
- src/pages/PrepareCondition/index.tsx
Closes #434
The same problem was in the filters. For prepare condition the min date is set to today.
> Call checkValidity and provide min-max parameters

- src/components/filters/CollateralFilterDropdown/index.tsx
> [FE] Move 'Custom Token' option to the bottom in the Collateral filter 

- src/config/networkConfig.ts
- src/hooks/usePositionsList.tsx
- src/queries/CTEConditions.tsx
- src/queries/CTEPositions.tsx
> Allow to search partially

- src/pages/ConditionsList/index.tsx
- src/pages/PositionsList/index.tsx
> Positions/Conditions list: Pagination is not reset to the 1st page after filters applying

- src/components/text/Hash/index.tsx
- src/pages/ConditionDetails/Contents.tsx
- src/pages/PositionDetails/Contents.tsx
Closes #355, also fixed a minor bug on modals for oracles/questions where the external link pointed to `.../undefined` 
Some fields were already there. Links to Omen markets are going to be addressed in #356 . Resolution details and TVL weren't added, they are extracted in another issue #526 that need a design (UX/UI) and confirmation about the feasibility of TVL with the current schema.
> Improve details of conditions and positions

- src/pages/ConditionDetails/Contents.tsx
- src/pages/ConditionsList/index.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/PositionsList/index.tsx
> [FE] Disable report payout option when a condition is resolved

- src/hooks/useCollateral.tsx
- src/pages/SplitPosition/index.tsx
- src/services/conditionalTokens.ts
- src/util/tools.ts
> [FE] Split Position Result Modal window appears when transaction is failed

- package.json
- src/components/layout/Footer/index.tsx
> (add) docs link to the footer

- src/components/common/TokenIcon/index.tsx
- src/config/networkConfig.ts
- src/pages/PositionsList/index.tsx
> Positions list: cDAI icon is blinking when open Collateral filter in mainnet

- src/components/form/CategoriesDropdown/index.tsx
> Omen Condition: Prepare button remains disabled until open and reselect a category

- src/pages/PrepareCondition/index.tsx
> fix link to duplicated condition

- src/pages/ConditionsList/index.tsx
- src/pages/PositionsList/index.tsx
> When disconnected, the app use default Rinkeby for the Network: it causes errors with filtering

- src/pages/ConditionsList/index.tsx
> Disable sorting by Reporter/Oracle in the Conditions list

- src/pages/PrepareCondition/index.tsx
> Prepare condition: 'working..' pop-up hangs when connect a wallet after pressing on the 'Prepare' button

- src/pages/MergePositions/Contents.tsx
- src/pages/PrepareCondition/index.tsx
- src/pages/RedeemPosition/Contents.tsx
- src/pages/ReportPayouts/Contents.tsx
- src/pages/SplitPosition/Form.tsx
> Nothing happens when click on the Ok button on the 'Are you sure you want to leave this page?' pop-up when navigate to the same page

- src/pages/RedeemPosition/index.tsx
> Redeem Positions heading is missing

- src/theme/tableCustomStyles.tsx
> (fix) double line

- public/index.html
- src/components/form/TextfieldFetchableData/index.tsx
- src/components/modals/EditPartitionModal/index.tsx
- src/components/statusInfo/Spinner/img/SpinnerSVG.tsx
> (Fix) Confirmation Message

- src/contexts/PositionContext.tsx
- src/pages/ConditionDetails/Wrapper.tsx
- src/pages/PositionDetails/Wrapper.tsx
Closes #578
Not sure about how correct the code to check if the position exists is (no errors where being pushed when a position wasn't found), but it seems to do the trick.
> (Fix) Show error when position is not found

- src/pages/PrepareCondition/index.tsx
> (fix) condition preview 

- src/components/filters/MinMaxFilter/index.tsx
- src/components/modals/CustomCollateralModal/index.tsx
- src/components/pureStyledComponents/Row.tsx
- src/pages/ConditionDetails/Contents.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/PrepareCondition/index.tsx
> (fix) don't show omen condition preview

- src/pages/PrepareCondition/index.tsx
> (fix) Custom condition preview not showing up

- .env.example
- src/config/constants.ts
- src/config/networkConfig.ts
- src/contexts/Apollo.tsx
Closes #632 
I think we don't need it, so I removed the ws configuration from the application
> Thegraph WebSocket is closed before the connection is established

- src/components/common/TokenIcon/index.tsx
No issue related, just added the `toChecksumAddress` to really fetch the image from the source.
> Add toChecksumAddress to the logo image

- src/components/table/SelectableConditionTable/index.tsx
> Disable sorting by Reporter/Oracle and QuestionID in the select condition section

- src/pages/ReportPayouts/Contents.tsx
Closes #652 
I go for the second solution ...
> Report button should be enabled and call connection pop-up on the Report payouts page

- src/components/form/ConditionsDropdown/index.tsx
- src/pages/MergePositions/Contents.tsx
> 'Use Position Balance ($0.00)' should be disabled when no positions to merge are selected

- src/components/layout/Footer/index.tsx
- src/components/pureStyledComponents/MainScroll.tsx
- src/components/pureStyledComponents/PageTitle.tsx
- src/pages/CookiePolicy/index.tsx
- src/pages/PrivacyPolicy/index.tsx
- src/pages/TermsAndConditions/index.tsx
> (Fix) Terms / Cookie / Privacy errors

- src/pages/ReportPayouts/Contents.tsx
> Report payouts: not to show 'At least one payout must be positive' warning until clear out all the payouts fields

- src/components/form/DisplayTableHashes/index.tsx
- src/components/form/OmenMarketsOrQuestion/index.tsx
- src/components/modals/DisplayHashesTableModal/index.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/PositionDetails/Wrapper.tsx
- src/pages/PositionsList/index.tsx
- src/util/types.ts
> Reality.eth is not displayed in the Oracles pop-up when there are 2 oracles for a position 

- .env.example
- src/components/common/TokenIcon/index.tsx
- src/config/constants.ts
> Setup logo endpoint as environment variable 

- src/components/pureStyledComponents/StripedList.tsx
- src/pages/ConditionDetails/Contents.tsx
> (fix) Word wrapping

- src/pages/CookiePolicy/index.tsx
- src/pages/TermsAndConditions/index.tsx
> (fix) Typos

- src/components/form/OmenMarketsOrQuestion/index.tsx
- src/pages/ConditionDetails/Contents.tsx
> (Fix) Double margin

- src/components/common/TokenIcon/index.tsx
- src/config/networkConfig.ts
> [Staging+Prod] cDAI icon is blinking when open Collateral filter in the Postitions list

- src/components/form/InputAmount/index.tsx
- src/pages/SplitPosition/Form.test.tsx
> 'Use Wallet Balance' remains to display wallet amount of DAI when switch to 'Position' option

- src/components/form/DisplayTableHashes/index.tsx
- src/components/form/DisplayTablePositions/index.tsx
- src/components/modals/DisplayHashesTableModal/index.tsx
- src/components/statusInfo/common.tsx
- src/components/table/SelectableConditionTable/index.tsx
- src/components/table/SelectablePositionTable/index.tsx
- src/pages/ConditionsList/index.tsx
- src/pages/PositionsList/index.tsx
> (Fix) Unnecessary buttons

- src/components/common/Dropdown/index.tsx
- src/components/filters/OraclesFilterDropdown/index.tsx
- src/components/form/CategoriesDropdown/index.tsx
- src/components/form/ConditionTypesDropdown/index.tsx
- src/components/form/SearchField/index.tsx
- src/components/form/SelectCollateral/index.tsx
> Previously selected option in filter dropdowns remain to be highlighted after Clear Filters 

- src/pages/RedeemPosition/Contents.tsx
> Redeem position preview section is missing when a position to redeem is not selected

- src/pages/MergePositions/Contents.tsx
- src/pages/SplitPosition/Form.tsx
Closes #560 
Fixed for the split section, can't reproduce the problem in the merge section (maybe fixed in another PR)
@elena-zh can you verify the fix ? please approve it if is OK, thanks
> 'Are you sure you want to leave this page?' pop-up appears after successful position creation/merge

- src/components/common/TokenIcon/index.tsx
- src/components/form/InputAmount/index.tsx
- src/pages/SplitPosition/Form.test.tsx
- src/pages/SplitPosition/SplitFrom.tsx
> Split position: The app is crashed when switch to the Position option

- src/components/filters/DateFilter/index.tsx
> Enable 'Clear' button as soon as a value appears in the Date filter

- src/config/networkConfig.ts
No issue related, should fix some problems related to the omen markets
To create a market use dxtest.eth.link
> Update oracle address

- .env.example
- src/config/constants.ts
- src/pages/PrepareCondition/index.tsx
- src/pages/RedeemPosition/Contents.tsx
No issue related, added a USE CPK env var
> Add USE_CPK env var

- src/components/filters/DateFilter/index.tsx
> Do not apply 3 sec of a delay when a date field is filled in with a correct value

- src/pages/ReportPayouts/Contents.tsx
- src/pages/ReportPayouts/OutcomesTable.tsx
Closes #642 
I applied some fixes, reported more than 20 conditions, and everything seems to be working OK.
Also, the payout is a vector with numbers, not float (if we send a float, the transaction triggers an error)
> Empty The reported array is displayed after successful report payouts

- src/components/filters/DateFilter/index.tsx
- src/pages/MergePositions/Contents.tsx
> Condition Id field is cleared out when select a position to merge with for a position with 2 conditions

- src/components/filters/DateFilter/index.tsx
- src/hooks/useCondition.tsx
- src/pages/MergePositions/Contents.tsx
- src/pages/RedeemPosition/Contents.tsx
- src/pages/ReportPayouts/Contents.tsx
- src/pages/SplitPosition/Form.tsx
> [FE] Add spinner to Outcomes table in "Report Payouts

- src/components/filters/DateFilter/index.tsx
- src/pages/ConditionsList/index.tsx
- src/pages/PositionsList/index.tsx
> Lists filter results are not reset after connecting to a wallet 

- src/components/filters/DateFilter/index.tsx
- src/pages/PrepareCondition/index.tsx
> Question/Outcomes/Category is not displayed in an Omen condition details when create in it the CTE

- src/components/filters/ConditionTypeFilterDropdown/index.tsx
> Filter by Condition type shows no conditions when select 'Omen Condition'

- src/components/form/DisplayTablePositions/index.tsx
> UI - Loader seems to be too big when positions are loaded on a condition details page

- src/components/table/SelectableConditionTable/index.tsx
- src/pages/ReportPayouts/Contents.tsx
- src/pages/SplitPosition/Form.tsx
> Reset filter results after connecting to a wallet on the Split position/Report payouts pages

- src/components/filters/MinMaxFilter/index.tsx
- src/components/pureStyledComponents/Textfield.tsx
- src/pages/ReportPayouts/OutcomesTable.tsx
> (fix) Firefox's number inputs arrows issue

- src/components/form/DisplayTablePositions/index.tsx
- src/pages/ConditionDetails/Contents.tsx
Closes #446 
After splitting looks the same
But in the detail
> Add collection column to condition's split positions

- src/contexts/Web3Context.tsx
- src/pages/Routes/index.tsx
> Add a descriptive message about unsupported testnets

- src/contexts/PositionContext.tsx
- src/hooks/useGraphMeta.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/PositionDetails/Wrapper.tsx
Closes #771 
I think is not necessary to add a loading, the problem is other thing, the wrapped collateral address wasn't being updated correctly
> Add 'Loading...' until a wrapped collateral address is loaded

- package.json
- src/contexts/Web3Context.tsx
- src/pages/MergePositions/Contents.tsx
- src/pages/PositionDetails/Contents.tsx
- src/services/conditionalTokens.ts
- src/services/cpk.ts
- src/services/reality.ts
- src/services/wrapper1155.ts
- src/util/tools.ts
- yarn.lock
> Report payouts/merge positions: the conditions/positions section is not auto-updated when a condition is resolved/positions merge

- src/contexts/Web3Context.tsx
- src/hooks/useActiveAddress.tsx
- src/hooks/useConditionsList.tsx
> Update app pages when switch on/off 'Use CPK Address' option

- src/hooks/usePositionsList.tsx
> Show loader when positions filtering by 'with balance' is running

- src/hooks/usePositionsList.tsx
- src/pages/MergePositions/Contents.tsx
- src/pages/RedeemPosition/Contents.tsx
- src/pages/ReportPayouts/Contents.tsx
Closes #800 
Closes #799 
Closes #333
> Fix some minor bugs related to CPK

- src/pages/RedeemPosition/Contents.tsx
> [FE] Redeemed position returns no tokens

- src/hooks/useConditionsList.tsx
- src/hooks/usePositionsList.tsx
- src/queries/CTEConditions.tsx
> [DEV] Positions list is not loaded to a not connected user

- package.json
- src/components/filters/DateFilter/index.tsx
> Fix moment/UTC use

- src/components/modals/UnwrapModal/index.tsx
- src/pages/PositionDetails/Contents.tsx
- src/services/erc20.ts
- src/util/tools.ts
- Add more decimals if balance is lower than 0.01
- Add token name from ERC-20 wrapper.
- Disable wrap button if there is already an ERC-20 wrapped.
- Add tokenBytes and accountTo to fix unwrap methon on Unwrap modal.
> Fix unwrap feature on position details
