gnosis/conditional-tokens-explorer

- .travis.yml
Fix a .travis.yaml CI script typo `development` to the right name branch `develop`.
> Fix .travis.yaml CI script to allow develop branch

- src/pages/MergePositions/Contents.tsx
- src/pages/PositionDetails/Contents.tsx
Closes #168 
I couldn't reproduce the original error, but from the screenshot, we can see that react is trying to render an object (an Error object). Also in that file, the error state was using `string | undefined` instead of `Maybe<Error>` as other components do. The only exception seems to be hooks that use strings for errors.
> Render error in merge positions

- src/components/modals/CustomCollateralModal/index.tsx
- src/components/splitPosition/PositionPreview/index.tsx
- src/hooks/useCollateral.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/SplitPosition/index.tsx
Closes #172 
This change `useCollateral` hook to return error and loading state. When you add a custom token in split position page we should see a spinner or an error. Errors have the original message, maybe this could be improved mapping common errors to a string.
> Use collateral with error and loading

- src/theme/globalStyle.tsx
- src/theme/walletConnectCSS.tsx
- src/theme/web3ModalCSS.tsx
Closes #178 
Related to #212 
Design's here: https://zpl.io/aMOdXk3
**A few notes about this:**
- It's not currently possible to modify the layout or functionality of _web3Modal_ in any officially supported way (https://github.com/Web3Modal/web3modal/issues/44), nor it's simple to do it in any unofficially supported way...
- ... but anyways I added some CSS to make it look more like it looks in the design.
- I used the wallet icons provided by the plugin. I think that - while not exactly the same seen on the design- they're fine.
- This is mostly related to #212, but - as stated- it's not possible to add a close button to this component. Addressing the "impossible to close" issue, it should be possible to close the modal by clicking the background overlay (which may not be obvious at …
> (Feature) Connect modal styles

- src/components/modals/EditPartitionModal/index.tsx
- src/components/splitPosition/PositionPreview/index.tsx
- src/hooks/usePositions.tsx
- src/pages/SplitPosition/Form.tsx
- src/pages/SplitPosition/index.tsx
Closes #67 
Closes #66 
- Allow to edit a partition, add or remove a collection
- Allways will generate the partition from the outcomeSlotCount, not from the collections of the condition
- The user, will need to add at least two collections, and all the outcomes (Please @lmcorbalan check this)
- Fix the comments in the original issues related to the sort, and how the circles are named.
>  Add Edit Partition to Split Position

- src/theme/walletConnectCSS.tsx
Closes #215 
Changed the `X` icon for the one we are using everywhere else, so it should look like this now:
> (fix) close icon double line

- src/pages/ConditionDetails/Contents.tsx
No related issue.
Just a minor nitpick: moved the _"Condition ID"_ data to the first position on _"Condition Details"_. It is the only place where a Condition / Position ID it's not the first item.
> (fix) condition id order

- src/components/common/TokenIcon/index.tsx
- src/pages/ConditionsList/index.tsx
- src/pages/PositionsList/index.tsx
Closes #248 
This should be working by default, and as an exception needs to use `ignoreRowClick` to not use `onRowClicked` but it doesn't seem to be configured in that way or any option disabling it, so I just added a handler that includes the row information.
> Custom handler for cell components

- src/pages/ReportPayouts/Contents.tsx
* Report payouts number is converted from BigNumber to number with the
ether/utils formatUnits. It was replaced by the BigNumber `toNumber`
method.
Close #222
> Replace `formatUnits` to `toNumber`

- src/components/splitPosition/DisplayTablePosition/index.tsx
- src/pages/SplitPosition/Form.tsx
Closes #277 
If this is solved in another pull request, just ignore.
> Fix ordering and jsx interpolation in modal after split

- src/components/form/BigNumberInputWrapper/index.tsx
Closes #255 
The BigNumberInput, is a common component used through all the application, so we need to check every section is working properly.
> Wrap and unwrap modals: cannot enter a value which starts with 0. into the Amount field 

- src/components/modals/SelectConditionModal/index.tsx
- src/hooks/useConditions.tsx
- src/hooks/usePositions.tsx
- src/pages/ConditionsList/index.tsx
- src/queries/conditions.tsx
Related to the issue #208 
This only fix the sort for the conditions, for the positions we need to wait until the issue https://github.com/gnosis/hg-subgraph/issues/19 could be fixed
> Implement default sort order for grid lines on the Conditions pages

- src/components/common/Modal/index.tsx
- src/components/statusInfo/common.tsx
Closes #360 
I'm not able to reproduce the problem, but I suspect it has something to do with the `line-height` property's value, so I increased it.
I think that'll do it.
> (fix) modal title's line height

- src/components/common/Modal/index.tsx
- src/components/statusInfo/common.tsx
Closes #360
I still can't reproduce the issue, but increased line height a little more.
> (fix) modal's title line height

- src/components/form/SelectPositions/index.tsx
Closes #376 
In my opinion, is a kind of weird behavior to have when there is a button to open the modal, but also I think we should close (related to this) the issue #227, because there is no point in removing a position if you not going to select another, and for that, we have the modal. 
I've created this as a draft because I removed the disabled attribute on the input of single positions and it could allow us to move to that input without clicking and pasting text to it. And maybe UX-wise point of view #376 could be removed if is not valid or friendly.
> Open single select position on click

- src/components/modals/SelectPositionsModal/index.tsx
- src/hooks/useWithToken.tsx
The Select positions modal mixture the `data` query obtained from `usePositions` with aditional token information on `useWithToken`. When the `data` array provided is empty, the `setDataWithToken` useState will return all positions list.
To avoid this was added a `setDataWithToken([])` in case the searched parameter `data` is empty.
Closes #285
> Select Positions modal: not found search return all positions

- src/components/form/DisplayTablePosition/index.tsx
- src/components/icons/ExternalLinkIcon.tsx
- src/components/table/CellHash/index.tsx
Closes #387
Related to #395
It should be fixed now.
> (fix) broken "open in new tab" link

- src/components/modals/UnwrapModal/index.tsx
- src/components/modals/WrapModal/index.tsx
- src/pages/PositionDetails/Contents.tsx
Closes #319 
Now look like this
The `None` word is used for both
Wrap and unwrap texts now  says `Use Position Balance...`
> [FE] Wrap/Unwrap: change 'Use Wallet Balance' to 'Use Position Balance'

- src/pages/SplitPosition/Form.tsx
After split a position from a given position id, the constant set to alias from `collateral` is already an assinged constant. Typescript and linter are not warning about that because the alias comes with double asignation. Maybe could be reported to the linter.
Closes #361
> Fix Split Position unassigned collateralToken from a given positionId

- src/components/buttons/ButtonSelect/index.tsx
- src/components/common/Dropdown/index.tsx
- src/components/form/Amount/index.tsx
- src/components/form/BigNumberInputWrapper/index.tsx
- src/components/modals/UnwrapModal/index.tsx
- src/components/modals/WrapModal/index.tsx
- src/pages/PositionDetails/Contents.tsx
- src/pages/PositionsList/index.tsx
Closes #454
- Wrap Collateral - reject / Unwrap collateral - reject / Transfer outcome tokens - reject: All of the status info windows' widths should be correct now.
- Users can use the enter key in the wrap / unwrap modals to submit the form now. We could do the same for other forms later, if it makes sense.
- Fixed a nested button console error.
> (Fix) Status info window's width

- src/services/conditionalTokens.ts
Closes #289 
This was more research than coding.
We were using a static method that uses some helpers provided by `id-helpers` to pre-calculate the resulting ids of making a split, this was working well for splitting from collateral but was failing if we split to deeper positions. For example, 
Condition: C
Collateral: $
If we made a split from $:C, we will get $:C1, $C2, $C4, and if we split again using the same condition, and position of indexSet 4, we will get $C4-1, $C4-2, and $C4-4, the id of the last case the id generated was different from the position actually created. This id didn't exist in the graph and neither has balance. Using `getCollectionId` from the contract and using that result to calculate the positionId solves the problem. 
Making another `getCollectionId` that …
> Use contract to calculate ids

- src/components/filters/OraclesFilterDropdown/index.tsx
- src/config/networkConfig.ts
- src/pages/PrepareCondition/index.tsx
Closes #474 
Closes #475
Also changed the order of the arbitrator's items to make Kleros appear first (besides it being the default option), and added a little note to explain what the oracle's address is for Omen conditions.
> (Fix) Remove Kleros from the oracles' filter, and make it the default arbitrator

- src/pages/ConditionsList/index.tsx
- src/theme/tableCustomStyles.tsx
Closes #459 
- Changed "Reporting Address / Oracle" for "Reporter / Oracle"
- Added a bit of more padding to the data cells to better separate the contents.
There's not much else that can be done (and it's worth the time), I think.
> (fix) Overlapping text

- src/components/form/DisplayTablePositions/index.tsx
Closes #482 
I couldn't get to reproduce the issue, but I suspect it has something to do with the screen's width and / or the first column's width (which wash fixed and isn't anymore).
It should be fixed now, but I can't be 100% sure.
> (fix) Link icon width

- src/components/filters/DateFilter/index.tsx
Closes #503 
Just to take into account:
The value of the Date input in this case is null
Also, the value of the Date input in this other case, is null
> Creation date: validation message is displayed when clear out any filter field 

- package.json
- src/components/common/TokenIcon/index.tsx
- src/config/networkConfig.ts
- src/hooks/useCollateral.tsx
- src/util/tools.ts
- yarn.lock
Closes #504 
@elena-zh I added the uniswap package, you can check it here https://gateway.ipfs.io/ipns/tokens.uniswap.org
We can't search a token by symbol, unless we have an array file with all the token information. For rinkeby, is really difficult to have a curated list of token, so the file is really small with only a couple of tokens. So, just to consider, I added this uniswap package, that includes a file with a list of curated tokens for mainnet (remember to test this in mainnet).
The search by symbol, only check for the first ocurrence of a match, not multiple checks, for example:
- Search the ren symbol
- There are no positions with the collateral ren
- But exist some positions If we search by renBTC symbol
- Maybe a good feature is to search all the words that starts with ren, …
> Add a possibility to search by a custom collateral symbol

- .travis.yml
- travis/deploy_release.sh
Setup production environment variable `REACT_APP_GOOGLE_ANALYTICS_ID` for production deployments.
This feature will separate the GA env vars from different environments.
> Setup production GA env var on Travis

- src/components/mergePositions/MergePreview/index.tsx
- src/components/pureStyledComponents/StripedList.tsx
- src/components/splitPosition/PositionPreview/index.tsx
- src/pages/PositionDetails/Contents.tsx
Closes #565
It should look something like these:
> (Fix) Overlapping lines

- src/theme/dataTableCSS.tsx
Closes #281
There's no (easy / official) way to change the sort icon's order. Check [here](https://github.com/jbetancur/react-data-table-component/issues/139#issuecomment-510662948) for some extra info _("Notice that right align columns have the icon left render and all other alignments have it on the right.")_
The same goes for always showing the icons (add to it that all the icons always point towards the same direction, regardless of what column is the sorting applied to).
So... I just added some padding to separate the icon a bit from the text. The rest is not worth the effort / time IMO.
> (Fix) Sort icon

- src/components/filters/MinMaxFilter/index.tsx
Closes #607
It should look like this now on Firefox.
> (fix) remove number input spinners on firefox

- src/pages/MergePositions/Contents.tsx
- src/util/tools.ts
Closes #611 
I was able to merge without any changes for the base case (positions c2c1p1 - c2c1p4 merged by c2), I just filtered conditions to avoid showing conditions shared in shallower positions.
For the record, the problem was that if you have a condition C1, and split it like this
``` 
$:C1:O1 (C1-P1)
$:C1:O2 (C1-P2)
```
The indexSet of C1-P1 will be `[1]` and for C1-P2 will be `[2]`, in both cases the conditionsIds will be [C1]
If we split again, using C1-P2, with C2 for example of 4 outcomes, we will get
```
C1-P2:C2:O1 [2 1] [C1 C2]
C1-P2:C2:O2 [2 2] [C1 C2]
C1-P2:C2:O3 [2 4] [C1 C2]
C1-P2:C2:O4 [2 8] [C1 C2]
```
And then we try to merge any number >= 2 of positions from that set using C1, we will get a partition with the form of [2 2] or [2 2 2], etc. This is a disjoint …
> Make impossible to merge positions using using conditions of shallower positions 

- src/components/table/SelectableConditionTable/index.tsx
- src/components/table/SelectablePositionTable/index.tsx
- src/theme/dataTableCSS.tsx
Closes #649
> Selected position/condition is not highlighted in the select position/condition sections
It's highlighted now.
> Also, the selection is not in bold (as it was discussed [here](https://altoros.slack.com/archives/C0147SJMANS/p1603120875007300))
I remember the chat, but I checked and designs' fonts are not bold. There's a reason for that, though: changing font weight on hover / state change tends to displace elements. That's why I usually don't do it. Font color is changed to a darker one, though.
> In addition, not selected position in the Merge with section should be in the same color.
I don't understand this.
> Selected - highlighted and in bold
Checkbox indicates selection, rows and fonts styling stay the same.
> (Fix) Set active rows styling

- src/components/form/DisplayTablePositions/index.tsx
Closes #674
I'm not entirely convinced with this fix, but whatever... Tables in the app have a fixed min height, and this is a table so it should stay the same height even if there is no content. But in this case is at the end of the details, and there's nothing after if so the user wouldn't usually see if data is loading or if content is pushed if the table changes height, so this shouldn't be an issue.
I any case, it's easy to revert if something bad happens.
It should look like this when empty:
No changes for tables with content:
> (Fix) Table height

- src/pages/MergePositions/Contents.tsx
Fix this comment https://github.com/gnosis/conditional-tokens-explorer/issues/653#issuecomment-734230449
> 'Use Position Balance ($0.00)' should be disabled when no positions to merge are selected

- src/components/filters/MinMaxFilter/index.tsx
Closes #630 
The error was that `+''` is 0, then it ran validateBounds that makes the min as 2 without changing the value in the input, if I change the ref there then it is impossible to enter something that starts with '1' because will be replaced by a '2'. Just to clarify, this was working in that way, if you search from 1 to 300 it would search from 2 to 256. The only possible error is given when searching for something with max > min. And for me, it is OK.
Also, if you remove the values and get the arrow disabled the search is not repeated, the bug is fixed but I'm not sure about the rest of the details about the UX of that input. In my opinion, if the user removes the values without using 'clear' is because they want to enter another pair of values, so it is OK for me too.
> Avoid interpreting empty string as 0

- src/pages/PositionsList/index.tsx
- src/pages/RedeemPosition/Contents.tsx
- src/util/tools.test.ts
- src/util/tools.ts
Closes #641 
Closes #643 
The `reduce` to calculate `parentCollectionId`  was wrong after some refactor or some kind of typo, I'm not sure. This was difficult to find during development because it only happens for positions of depth > 1, also the redeem was only showing positions with all the conditions resolved. I've fixed that and created a few tests after extracting that functionality outside the component.
@elena-zh I think the test cases here are
- positions with all conditions resolved should give collateral (1)
- positions with some conditions resolved should give outcome tokens
- positions without conditions resolved shouldn't be available for redeeming.
For simplicity, C1, C2 and C3 will have only 2 outcomes.
(1)
```
10DAI + C1 => 10 C1P1 + 10C1P2
10 C1P1 + C2 => 10C1C2P1 + …
```
> Fix regression in redeem

- src/components/form/DisplayTableHashes/index.tsx
- src/components/modals/DisplayHashesTableModal/index.tsx
Closes #627
> Still, 'Navigate' icon is displayed in a separate line when an omen market text fits (...)
That's OK, it follows the natural flow of text. Doing anything else would be time consuming for something the user won't see too often.
> Questions (markets) are not wrapped, copy and navigate icons are displayed (...)
For this case I simply cut the text gracefully. It should fit now.
> Questions (markets) are placed in the order 'Last created at the top' in the Omen Markets pop-up (...)
I don't know if this is a problem (isn't that the default order?), but if it is I don't know how to fix it. I wouldn't change it, not a big deal.
> Sometimes Omen Market(s) section is blinking after being loaded (...)
I think Elena and I talked about this in another PR, and she probably created an …
> (Fix) UI issues with 'Omen Market(s)'

- src/components/filters/WithBalanceFilterDropdown/index.tsx
- src/hooks/usePositionsList.tsx
- src/pages/PositionsList/index.tsx
- src/util/types.ts
Closes #750
That is what Auryn asked in the last sync. Is just a client-side filter function passed to the actual hook for positions. 
Maybe we can use that kind of filtering for everything but is not a big improvement if we continue using 'no-cache', because we will need to fetch everything in sections where the query narrows the result. Doing this full fetch only once seems fine but in each positions fetch can be a problem right now.
> Pass filter to usePositionsList to only show positions with balance

- src/queries/CTEConditions.tsx
- src/types/generatedGQLForCTE.ts
Closes #752 
This type checks correctly and works as far as I tested. Querying positions for conditions seems like something that was left by an old feature or another approach to solve something else and doesn't seems to be used anymore. This and the improvements in the index from @davidalbela should make that conditions list works again (and hopefully faster than before).
> Remove positions from fragment

- src/pages/PrepareCondition/index.tsx
Closes #617 
I'm not sure where to put the "clear" text. I've used a component used for filters but maybe it should be right-aligned. The errors of `resolutionDate` are cleared too.
> Add clear date to prepare condition

- src/components/common/Dropdown/index.tsx
- src/components/common/PageOptions/index.tsx
- src/hooks/useLocalStorageValue.tsx
Closes #658 
Table container should fill all available height now, so dropdowns should be always fully visible (even if there are only a few rows).
Only possible exception is when screen height is extremely low.
**Note:** all of the table's dropdowns are going away on the next design iteration, so let's not spend a lot of time dealing with this.
**Screenshot:**
> (fix) Cut dropdown

- src/pages/PositionsList/index.tsx
Closes #768 
Closes #769 
Those "bugs" seem like a feature, without using localStorage we can get the reset of filters on network change, but maybe the idea was to maintain the config by network-status, so I change the key according to that.
> Save columns shown in position list by networkName and status

- src/services/cpk.ts
Closes #773 
1 step. create a condition
2. split positions for it (C1P1+C1P2)
3. create condition C2
4. split: condition C2+ select position option (and use C1P1). Do not split the whole amount. split 1 token, as an example (edited) 
and you will see than an additional token (1) is taken from the wallet balance. but it should not behave this way
no additional tokens can be taken when split a position  using the 'Position' option
> Complex split: an additional token's amount is taken from the wallet when split position

- src/components/partitions/Outcome/index.tsx
- src/pages/SplitPosition/Form.tsx
- src/queries/CTEConditions.tsx
- src/types/generatedGQLForCTE.ts
- src/util/types.ts
Closes #753 
This has something for #543 
Look like this. For long outcomes names, I think we should use only the id inside the circle and value by the side.
> Add spinner  while outcomes load

- src/components/form/AddOutcome/index.tsx
- src/pages/PrepareCondition/index.tsx
Closes #479 
A message of unsaved changes is shown below the outcomes block only when everything else is completed. I think  we can
- Change the message to live inside `AddOutcome` 
- Always show the message, and use the proper component according to their final position
- Maybe we can just disable the submit, or making something more subtle.
Also, I wasn't sure if the possibility of editing multiple outcomes at the same time is desirable or not.
> Unsaved Changes

- package.json
- src/contexts/MultiPositionsContext.tsx
- src/contexts/PositionContext.tsx
- src/hooks/useQueryTotalResults.tsx
Limit to 5000 the `skip` value on the GQL position list. GQL has a limit of 5000 element for the skip parameter.
> Hotfix Position List skip limit GQL

- RELEASES.md
- package.json
- Bump url-parse from 1.5.1 to 1.5.3 #861
- Enable Wrap button for Position Details #1914d5a
- Disable Wrap and Unwrapp features from Position list #e7cde29
- Fix React Hook useCallback has missing dependencies from Unwrap modal #b2db9fc
- Fix formatBigNumber format check #e364b6d
> Bump version `v0.3.2`
